// import * as S from "./layout.styles"

import { AppDrawer } from "@/app/components";
import ThemeProvider from "@/app/providers/ThemeProvider";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Next MUI Projects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <head></head>
        <body className={roboto.className}>
          <AppDrawer>{children}</AppDrawer>
        </body>
      </html>
    </ThemeProvider>
  );
}
