import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import ThemeProvider from "@/app/providers/ThemeProvider";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Next MUI Projects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <head></head>
        <body className={roboto.className}>
          <ul>
            <li>
              <Link href="/">Home Page</Link>
            </li>
            <li>
              <Link href="/project_1">Project 1</Link>
            </li>
            <li>
              <Link href="/project_2">Project 2</Link>
            </li>
          </ul>
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
